dist: trusty
sudo: required

notifications:
  email:
    - 00hnes@gmail.com

language: c

compiler:
  - gcc
  - clang

install:
    - sudo apt-get install -qq -y libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make build-essential valgrind gcc-multilib g++-multilib libc6-dbg libc6-dbg:i386
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-key update
    - sudo apt-get install -y gcc-7 gcc-7-multilib 
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
    
script:
    - echo $TRAVIS_EVENT_TYPE
    - ulimit -c unlimited
    - cat /proc/cpuinfo && free -m && uname -a
    - gcc-7 --version
    - gcc --version
    - ls /usr/include
    - ls /usr/include/valgrind
    - date
    - ls -hl
    - bash libco_bug_build.sh
    - ls -hl
    - gcc -c coctx_swap.S -o coctx_swap.o
    - objdump -Mintel -d coctx_swap.o
    - ./test_m32_libco_benchmark
    - ./test_libco_benchmark
